# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# Crear diccionario con datos
datos = {
    "Producto": ["Camara ip", "Camara wifi", "Camara analogica", "Domo PTZ", "Camara 4 lentes"],
    "Precio": [250000, 155000, 95000, 1100000, 890000],
    "Cantidad": [32, 15, 25, 28, 17]
}

# Crear DataFrame
df = pd.DataFrame(datos)

# Mostrar DataFrame
print(df)

# Operación entre columnas
df["Total"] = df["Precio"] * df["Cantidad"]

# Mostrar resultado
print(df)

# Aplicar descuento del 16%
df["Descuento"] = df["Total"] * 0.16

# Total final
df["Total_Final"] = df["Total"] - df["Descuento"]

print(df)

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("ventas.csv")

print(df)